name: getx_lint_example
description: Yeet GetX lint rule example.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  custom_lint: ^0.0.9+1
  getx_lint:
    path: ./getx_lint

flutter:
  uses-material-design: true
